### ISSUE TITLE
Excluir Membro da Equipe

### ISSUE THREAD

**Issue by yuryalencar** [ProjetoESE/Thoth#126]
Quando clica para apagar um integrante do projeto temos isso:

![image](https://user-images.githubusercontent.com/19940344/58998397-e5d1e500-87d6-11e9-9f69-be5d55fe9005.png)

**Comment by guilhermebolfe11** [comment]
Qual o nivel do integrante?

**Comment by guilhermebolfe11** [comment]
#132 
Este erro já foi corrigido
