### ISSUE TITLE
Bug: "Check duplicates" automático com problema

### ISSUE THREAD

**Issue by monred** [ProjetoESE/Thoth#139]
Há um recurso chamado "Check duplicates", onde parece que a intenção é checar automaticamente os artigos duplicados do estudo. 

Ao utilizar o recurso, verifiquei manualmente e havia pelo menos um artigo duplicado vindo de bases de dados diferentes que não foram identificados como duplicados.

**Comment by PedroSebastian** [comment]
Também identifiquei o problema. Acredito que seja ocasionado pela diferenciação de caracteres maiúsculos e minúsculos, tendo em vista que em uma base o título do artigo era apresentado com as palavras iniciadas em letra maiúscula e em outras em letra minúscula.
