### ISSUE TITLE
Dependendo da quantidade de artigos o bib não é importado

### ISSUE THREAD

**Issue by julianamareco** [ProjetoESE/Thoth#14]
Bib fica carregando mas não sobe

**Comment by guilhermebolfe11** [comment]
![import 350](https://user-images.githubusercontent.com/19590468/47825647-cf9c0c00-dd51-11e8-85c4-58b526e54190.PNG)
![640](https://user-images.githubusercontent.com/19590468/47825660-dfb3eb80-dd51-11e8-9ff3-a1b6f378a499.PNG)
 
Importei um com +350 e outro de +600 foi normal
