### ISSUE TITLE
Não está deletando o bib da Scopus

### ISSUE THREAD

**Issue by julianamareco** [ProjetoESE/Thoth#15]

**Comment by guilhermebolfe11** [comment]
![deletescopus](https://user-images.githubusercontent.com/19590468/47825619-b8f5b500-dd51-11e8-9a1d-cc7e19b5f479.PNG)
![import 350](https://user-images.githubusercontent.com/19590468/47825620-b98e4b80-dd51-11e8-86fb-f80b9911e8de.PNG)

**Comment by guilhermebolfe11** [comment]
importei e deletei normalmente
