### ISSUE TITLE
alterar gráfico de funil

### ISSUE THREAD

**Issue by lucianoMarchezan** [ProjetoESE/Thoth#27]
No gráfico de funil, add os dados referentes aos duplicados removidos e remova estes dados do gráfico de pizza

**Comment by guilhermebolfe11** [comment]
Poderia explicar melhor essa sua ideia, você gostaria de tirar a informação dos duplicados do gráfico de pizza (Primeira imagem) e colocar no funil (Segunda Imagem)?
![duplicados](https://user-images.githubusercontent.com/19590468/49393768-54939000-f719-11e8-8814-1a0408a88201.PNG)
![funnel](https://user-images.githubusercontent.com/19590468/49393769-54939000-f719-11e8-9a48-d3396b8dd7f2.PNG)

**Comment by lucianoMarchezan** [comment]
Isso

**Comment by guilhermebolfe11** [comment]
Seria algo assim? 
![01](https://user-images.githubusercontent.com/19590468/49443155-d4216d80-f7b2-11e8-9469-1f996ac98c28.PNG)
![02](https://user-images.githubusercontent.com/19590468/49443157-d4ba0400-f7b2-11e8-85c9-b39eee4aee76.PNG)

**Comment by lucianoMarchezan** [comment]
Isso ai
