### ISSUE TITLE
Permitir que edite o formulário de extração dos papers

### ISSUE THREAD

**Issue by lucianoMarchezan** [ProjetoESE/Thoth#28]

**Comment by guilhermebolfe11** [comment]
Poderia especificar melhor a funcionalidade que você deseja, obrigado

**Comment by lucianoMarchezan** [comment]
Depois que eu faço a extração de dados de um artigo e clico em DONE, o formulário de extração daquele artigo desaparece. Seria bom que ele ficasse ativo para que o usuário possa editar.

**Comment by lucianoMarchezan** [comment]
![image](https://user-images.githubusercontent.com/22458623/49184632-12e49d00-f347-11e8-9aff-8d0e5a3267a5.png)

**Comment by guilhermebolfe11** [comment]
A correção já foi realizada e logo estará disponivel
