### ISSUE TITLE
Grafico de QAS

### ISSUE THREAD

**Issue by lucianoMarchezan** [ProjetoESE/Thoth#30]
remove o grafico de pizza de QAs e add um gráfico de barras laterias mostrando quantos artigos pontuaram para cada score de cada QA. Considera apenas os artigos avaliados por QA, ignora os q foram excluidos antes.  Exemplo de grafico em anexo
![image](https://user-images.githubusercontent.com/22458623/49183161-56d5a300-f343-11e8-95ca-22d7cbe6a20e.png)

**Comment by guilhermebolfe11** [comment]
Essa funcionalidade pode não ser atendida a tempo, devido a uma inconsistência no banco, vou focar nas outras e se der ou resolver essa
