### ISSUE TITLE
Permitir visualizar as regras de avaliação das QA

### ISSUE THREAD

**Issue by lucianoMarchezan** [ProjetoESE/Thoth#32]
na tela onde as QA são respondidas, seria bom add uma forma de visualizar a descrição de cada score: Total - artigo apresenta validação;
Parcial - não apresenta validação.
Etc....

**Comment by guilhermebolfe11** [comment]
Coloquei um Tooltip em cada opção do select, é só colocar o cursor por cima e vai aparecer a descrição.
![02](https://user-images.githubusercontent.com/19590468/49598132-286c4f00-f965-11e8-92e7-462e4437b3da.PNG)

**Comment by guilhermebolfe11** [comment]
Coloquei um Tooltip para apresentar a descrição de cada valor no select, é so colocar o cursos por cima que aparece.

![02](https://user-images.githubusercontent.com/19590468/49598287-6e291780-f965-11e8-8261-d42f40a4e0c1.PNG)
