### ISSUE TITLE
Problema ao excluir questão do formulário de extração

### ISSUE THREAD

**Issue by lucianoMarchezan** [ProjetoESE/Thoth#35]
Eu removo uma questão do form de extração mais quando aperto f5 ela volta 
questão que desejo remover
![image](https://user-images.githubusercontent.com/22458623/49663163-ee6a7e00-fa34-11e8-9f70-9f91e4b4dc71.png)

Após remover
![image](https://user-images.githubusercontent.com/22458623/49663175-f62a2280-fa34-11e8-8d06-89de109fe069.png)

Após dar f5
![image](https://user-images.githubusercontent.com/22458623/49663184-fd513080-fa34-11e8-83d1-b6a10933d5b2.png)

**Comment by lucianoMarchezan** [comment]
Pelos testes que fiz aqui, parece que o problema é que já havia uma questão com o mesmo nome. Agora o bd não deixa excluir nenhuma

**Comment by guilhermebolfe11** [comment]
Acabei de resolver esse problema logo estará no ar, Vlw
