### ISSUE TITLE
Permitir fazer download de dados em .doc ou latex

### ISSUE THREAD

**Issue by lucianoMarchezan** [ProjetoESE/Thoth#36]
resumo dos critérios de qualidade, com tabela contendo os dados como o exemplo abaixo. Poderia dar a opção do usuário selecionar se quer que apareça a descrição da nota (GOOD, BAD) ou o valor (1,2,10)
![image](https://user-images.githubusercontent.com/22458623/49663995-a567f900-fa37-11e8-9863-171488b1a3d1.png)

Outro dado importante são os dados dos formulários de extração. O ideal seria permitir fazer o download dos dados no formato Excel.  Pare este caso pode utilizar alguma coisa presente nesse tutorial: https://www.the-art-of-web.com/php/dataexport/

**Comment by guilhermebolfe11** [comment]
Consegui fazer para exportar essa tabela para pfd, excel, csv e imprimir. depois vou implementar nas outras tabelas
