### ISSUE TITLE
Contagem errada ou artigos duplicados

### ISSUE THREAD

**Issue by julianamareco** [ProjetoESE/Thoth#37]
Se eu contar a quantidade de artigos que tem tags tem 1136
![capturar01](https://user-images.githubusercontent.com/19584543/49685948-502df500-fad4-11e8-9d4d-45890671aea2.JPG)

Mas foram importados 1078
![capturar02](https://user-images.githubusercontent.com/19584543/49685950-56bc6c80-fad4-11e8-9281-9fa912d9c5a8.JPG)

Um exemplo que ta duplicando é o seguinte, eu tenho um artigo que diz ser duplicado
![capturar](https://user-images.githubusercontent.com/19584543/49685964-89666500-fad4-11e8-832c-9c4471c0a7f6.JPG)

Mas ele não está na iee, nem na science direct, nem na acm, nem na springer link, nem na engineering village 

![capturar1](https://user-images.githubusercontent.com/19584543/49685981-be72b780-fad4-11e8-92c4-5d3cdaa495f1.JPG)
![capturar2](https://user-images.githubusercontent.com/19584543/49685983-c2063e80-fad4-11e8-9346-32284055b665.JPG)
![capturar3](https://user-images.githubusercontent.com/19584543/49685986-c6325c00-fad4-11e8-9de9-c429f0f0ef7d.JPG)
![capturar4](https://user-images.githubusercontent.com/19584543/49685987-c9c5e300-fad4-11e8-9b9d-dccc79bf6b43.JPG)
![capturar5](https://user-images.githubusercontent.com/19584543/49685988-ce8a9700-fad4-11e8-87b2-b7ade1d6fc95.JPG)

Ele está apenas na scopus e lá só tem um artigo com esse nome e o duplicado veio de algum lugar que não sei 

![capturar6](https://user-images.githubusercontent.com/19584543/49685997-e3672a80-fad4-11e8-9ace-24fdca03b2bc.JPG)

**Comment by guilhermebolfe11** [comment]
Esse pode ser um problema no import dos bib, caso você importou algum sem selecionar a Base de Dados, os artigos ficam desvinculados.
