### ISSUE TITLE
Deletar bibs

### ISSUE THREAD

**Issue by gutogirardon** [ProjetoESE/Thoth#38]
**Não funciona**
Não consigo deletar papers enviados via .bib.

Clico no ícone da lixeira (deletar) porém os arquivos não são deletados, seguem contabilizados no sistema.

**Comment by VictorSCosta** [comment]
Este problema é referente a chaves estrangeiras da tabela paper. É necessario definir a propriedade ON DELETE CASCADE nas tabelas que possuem chave estrangeira de paper (inclusion_criteria_selected, exclusion_criteria_selected, extraction_response, etc...).

Eu consertei o bug na produção mas é necessário atualizar o SQL para refletir as mudanças.
