### ISSUE TITLE
Nome de autores estão com problemas

### ISSUE THREAD

**Issue by lesseUnipampa** [ProjetoESE/Thoth#5]
Como mostrado na figura, alguns nomes não estão com acentuação correta.
![capturar](https://user-images.githubusercontent.com/43017380/46825213-7865d580-cd69-11e8-80ba-7ac671f67d75.PNG)

**Comment by guilhermebolfe11** [comment]
Em qual tela isso ocorre?

**Comment by lucianoMarchezan** [comment]
Tela onde aparecem a lista de artigos para se aplicar os critérios de i/e

**Comment by guilhermebolfe11** [comment]
Provavelmente problema é  no formato que o banco foi criado.
